print("Hello\"World\"World")
print('I\'m Harshad')
print("line A")
print("line B")
print("line A\nline B")
print("Harshad\tLande")
print("this is backslash\\")
print("this is double backslash\\\\")
print("Hell\blo")