/*script generated for free with OnlineDataGenerator available at: https://www.onlinedatagenerator.com */
CREATE TABLE MOCKDATA(ID BIGINT,JobTitle VARCHAR(500),EmailAddress VARCHAR(500),FirstNameLastName VARCHAR(500));

INSERT INTO MOCKDATA VALUES('1','Pharmacist','Dakota_Mason9259@jiman.org','Dakota Mason');
INSERT INTO MOCKDATA VALUES('2','Software Engineer','Carter_Ellis786@naiker.biz','Carter Ellis');
INSERT INTO MOCKDATA VALUES('3','Web Developer','Matt_Brooks108@irrepsy.com','Matt Brooks');
INSERT INTO MOCKDATA VALUES('4','Lecturer','Boris_Wood2695@bauros.biz','Boris Wood');
INSERT INTO MOCKDATA VALUES('5','Ambulatory Nurse','David_Hill3548@ovock.tech','David Hill');
INSERT INTO MOCKDATA VALUES('6','Inspector','Ada_Wright1471@corti.com','Ada Wright');
INSERT INTO MOCKDATA VALUES('7','Chef Manager','Nancy_Todd2435@extex.org','Nancy Todd');
INSERT INTO MOCKDATA VALUES('8','Chef Manager','Emerald_Johnson9144@tonsy.org','Emerald Johnson');
INSERT INTO MOCKDATA VALUES('9','Doctor','Ethan_Mccormick1898@acrit.org','Ethan Mccormick');
INSERT INTO MOCKDATA VALUES('10','Assistant Buyer','Mike_Willis1504@womeona.net','Mike Willis');
INSERT INTO MOCKDATA VALUES('11','IT Support Staff','Mark_Asher5171@sveldo.biz','Mark Asher');
INSERT INTO MOCKDATA VALUES('12','Budget Analyst','William_Thomson3942@mafthy.com','William Thomson');
INSERT INTO MOCKDATA VALUES('13','Front Desk Coordinator','Sarah_Yates5270@qater.org','Sarah Yates');
INSERT INTO MOCKDATA VALUES('14','Doctor','Ruby_Dallas2855@twace.org','Ruby Dallas');
INSERT INTO MOCKDATA VALUES('15','Cash Manager','Amy_Simpson4300@elnee.tech','Amy Simpson');
INSERT INTO MOCKDATA VALUES('16','Operator','John_Hammond2809@naiker.biz','John Hammond');
INSERT INTO MOCKDATA VALUES('17','Auditor','Noah_Snell7480@gmail.com','Noah Snell');
INSERT INTO MOCKDATA VALUES('18','Cook','Rocco_Rogers9869@hourpy.biz','Rocco Rogers');
INSERT INTO MOCKDATA VALUES('19','Steward','Hank_Sawyer9876@bungar.biz','Hank Sawyer');
INSERT INTO MOCKDATA VALUES('20','Associate Professor','Ethan_Lynch1996@liret.org','Ethan Lynch');
INSERT INTO MOCKDATA VALUES('21','Physician','Carl_Ross8151@grannar.com','Carl Ross');
INSERT INTO MOCKDATA VALUES('22','Steward','Miley_Styles665@iatim.tech','Miley Styles');
INSERT INTO MOCKDATA VALUES('23','Design Engineer','Claire_Carpenter7733@sheye.org','Claire Carpenter');
INSERT INTO MOCKDATA VALUES('24','Web Developer','Adalind_Emmett9789@ubusive.com','Adalind Emmett');
INSERT INTO MOCKDATA VALUES('25','Bookkeeper','Kimberly_Jenkin3757@yahoo.com','Kimberly Jenkin');
INSERT INTO MOCKDATA VALUES('26','Cook','Danny_Groves3081@jiman.org','Danny Groves');
INSERT INTO MOCKDATA VALUES('27','Mobile Developer','Carina_Skinner2679@guentu.biz','Carina Skinner');
INSERT INTO MOCKDATA VALUES('28','Audiologist','Gabriel_Garner45@muall.tech','Gabriel Garner');
INSERT INTO MOCKDATA VALUES('29','Loan Officer','Elise_Andrews8446@fuliss.net','Elise Andrews');
INSERT INTO MOCKDATA VALUES('30','Ambulatory Nurse','Rufus_Fox3425@famism.biz','Rufus Fox');
INSERT INTO MOCKDATA VALUES('31','CNC Operator','Fred_Brett9593@womeona.net','Fred Brett');
INSERT INTO MOCKDATA VALUES('32','Investment  Advisor','William_Jennson8824@liret.org','William Jennson');
INSERT INTO MOCKDATA VALUES('33','Project Manager','Daniel_Robinson1975@grannar.com','Daniel Robinson');
INSERT INTO MOCKDATA VALUES('34','Executive Director','Shelby_Booth9122@kideod.biz','Shelby Booth');
INSERT INTO MOCKDATA VALUES('35','Web Developer','Julius_Walter7500@bulaffy.com','Julius Walter');
INSERT INTO MOCKDATA VALUES('36','IT Support Staff','Elijah_Atkinson5942@twipet.com','Elijah Atkinson');
INSERT INTO MOCKDATA VALUES('37','Assistant Buyer','Camellia_Patel6340@bauros.biz','Camellia Patel');
INSERT INTO MOCKDATA VALUES('38','Doctor','Bart_Parr3461@typill.biz','Bart Parr');
INSERT INTO MOCKDATA VALUES('39','Cook','Hadley_Ward4725@muall.tech','Hadley Ward');
INSERT INTO MOCKDATA VALUES('40','IT Support Staff','Makenzie_Hale4851@sheye.org','Makenzie Hale');
INSERT INTO MOCKDATA VALUES('41','Doctor','Emely_Ellery4462@elnee.tech','Emely Ellery');
INSERT INTO MOCKDATA VALUES('42','Health Educator','Chad_Gardner2276@corti.com','Chad Gardner');
INSERT INTO MOCKDATA VALUES('43','Stockbroker','Gil_Leslie6186@nimogy.biz','Gil Leslie');
INSERT INTO MOCKDATA VALUES('44','Cashier','Holly_Vollans5970@liret.org','Holly Vollans');
INSERT INTO MOCKDATA VALUES('45','Treasurer','Elle_Robinson3805@twace.org','Elle Robinson');
INSERT INTO MOCKDATA VALUES('46','Auditor','Barry_Vane6285@joiniaa.com','Barry Vane');
INSERT INTO MOCKDATA VALUES('47','Physician','Enoch_Uttridge2222@ovock.tech','Enoch Uttridge');
INSERT INTO MOCKDATA VALUES('48','Physician','Mark_Rose8946@muall.tech','Mark Rose');
INSERT INTO MOCKDATA VALUES('49','Investment  Advisor','Paula_Mcgregor8715@nanoff.biz','Paula Mcgregor');
INSERT INTO MOCKDATA VALUES('50','Food Technologist','Vivian_Skinner4096@iatim.tech','Vivian Skinner');

